import NavbarWrapper from "./components/NavbarWrapper";
import { AccessTokenProvider } from "./context/AccessTokenContext";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Golden Future Institute",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AccessTokenProvider>
        <NavbarWrapper/>
        <main>{children}</main>
        </AccessTokenProvider>
      </body>
    </html>
  );
}
